spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: live.smtp.mailtrap.io
    port: 587

midtrans:
#  isProduction: true
  isProduction: false

oci:
  config:
    authType: INSTANCE_PRINCIPAL


