spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: live.smtp.mailtrap.io
    port: 587

midtrans:
  isProduction: true

oci:
  config:
    authType: INSTANCE_PRINCIPAL

