server:
  port: 9090

spring:
  application:
    name: warehouse
  profiles:
    active: ${PROFILES:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:warehouse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
app:
  mail:
    from: ${MAIL_FROM}
    name: ${MAIL_NAME}

transaction:
  taxRate: ${TRANSACTION_TAX_RATE:0}

midtrans:
  serverKey: ${MIDTRANS_SERVER_KEY}
  isProduction: ${MIDTRANS_IS_PRODUCTION:false}

telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  baseUrl: ${TELEGRAM_BASE_URL:https://api.telegram.org}

oci:
  config:
    path: ${OCI_CONFIG_PATH:~/.oci/config}
    profile: ${OCI_CONFIG_PROFILE:DEFAULT}
    namespace: ${OCI_OBJECTSTORAGE_NAMESPACE:axy64om8r4us}
    region: ${OCI_OBJECTSTORAGE_REGION:ap-batam-1}
    bucket: ${OCI_OBJECTSTORAGE_BUCKET:bakedbyerina}
    authType: ${OCI_CONFIG_AUTH_TYPE:CONFIG_FILE}
    bucketPublic: ${OCI_OBJECTSTORAGE_BUCKET_PUBLIC:true}

cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allowedMethods: ${CORS_ALLOWED_METHODS:*}
  allowedHeaders: ${CORS_ALLOWED_HEADERS:*}
  allowedCredentials: ${CORS_ALLOWED_CREDENTIALS:true}
  maxAge: ${CORS_MAX_AGE:3600}

logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

management:
  server:
    port: 8000
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /warehouse/actuator